name: "IM"
mode: "dev"
version: "0.0.1"
start_time: "2024-09-22"
machine_id: 0
port: 8080

log:
  level: "debug"
  filename: "./log/debug.log"
  max_size: 200
  max_age: 30
  max_backups: 7
  compress: false

mysql:
  username: "root"
  password: "123456"
  addr: "127.0.0.1"
  port: 3306
  dbname: "im"
  max_open_conns: 100
  max_idle_conns: 10

websocket:
  port: 8081

rabbitmq:
  url: "amqp://guest:guest@172.17.175.38:5672/"